name: Build Bouncy Hsm
on:
  workflow_dispatch
  
jobs:
  Build-linux-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build application
        run: |
          cd build_linux
          make build64
          rm -f *.o
          make build32
      - name: Upload linux native artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-native-libs
          path: |
            build_linux/*.so
          retention-days: 1


