name: Build Bouncy Hsm
on:
  workflow_call
  
jobs:
  Build-linux-libs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd build_linux
      - name: Build application
        run: make build64
      - name: Upload linux native artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-native-libs
          path: |
            build_linux/*.so

